### ISSUE TITLE
rev/cut: No such file or directory

### ISSUE THREAD

**Issue by sshaikh** [AladW/aurutils#898] opened 2022-01-21 16:41 UTC
__Before filing a bug, check the following:__

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?

Yes

2) Does the package conform to 
[`PKGBUILD(5)`](https://www.archlinux.org/pacman/PKGBUILD.5.html) and the 
[AUR package guidelines](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)?

As far as I can tell yes.

3) Does the package provide the correct metadata on the 

Yes

4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?

Yes

5) Does the package use internal `makepkg` functions? (see [FS#43502](https://bugs.archlinux.org/task/43502))

No, but it does run some commands in preparation (see below)

6) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?

Yes

[aurutils.log](https://github.com/AladW/aurutils/files/7915248/aurutils.log)

========================

I have a particular package on the aur https://aur.archlinux.org/packages/nvim-packer-git/ which throws errors on aur-srcver:

```
❯ aur srcver .
PKGBUILD: line 9: rev: No such file or directory
PKGBUILD: line 9: cut: No such file or directory
PKGBUILD: line 9: rev: No such file or directory
nvim-packer-git	r475.7182f0d-1
```

The trouble seems to be with line 9 of the PKGBUILD:

```
_reponame="$(echo "${url}" | rev | cut -d/ -f1 | rev)"
```

Interestingly `makepkg --skipinteg -od` completes without error, so I presume this is an ~~chroot~~ env issue or similar. It should be noted that the non-error output of the command is actually correct (although I cannot tell if it would have been correctly updated by `aur srcver`, or just taking the existing version)

**Comment by Earnestly** [comment] 2022-01-21 16:57
The `PKGBUILD` doesn't include `util-linux` or `coreutils` as `makedepends` which provide `rev` and `cut`.  Although `base-devel` does not include `coreutils`, I am surprised it isn't available somehow.

As an aside that level of abstraction is utterly ridiculous, especially when done so poorly.  (`_reponame=${url##*/}`)

**Comment by sshaikh** [comment] 2022-01-21 17:01
I didn't think such variable set ups needed or even could specify requirements via makedepends (as they run before dependencies are retrieved). But if it's definitely an issue with the pkgbuild I'd be happy to report it to the author.

**Comment by sshaikh** [comment] 2022-01-21 17:02
Oh and fwiw, aur utils does build the package correctly, so it's just aur srcver that has the issue.

**Comment by AladW** [comment] 2022-01-23 13:23
The issue is because aur-srcver sources the PKGBUILD with an empty environment, i.e. PATH is unset. There's usually no reason for PKGBUILDs to use commands outside of the packaging functions, and a replacement with bash parameter substitution is pointed out above.

On Fri, 21 Jan 2022 09:03:01 -0800
sshaikh ***@***.***> wrote:

> Oh and fwiw, aur utils does build the package correctly, so it's just aur srcver that has the issue.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/898#issuecomment-1018692193
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>


-- 
alad ***@***.***>

**Comment by sshaikh** [comment] 2022-01-23 14:20
Thanks for confirming that. Is this an AUR policy thing?

I ask as I also see similar issues while building another package:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pulseaudio-module-xrdp

which requires the pulseaudio binary to be available to extract a version from to download the correct make dependency.

Rather than bespoke fixes, it would be good if I can point the maintainers to some respective advice on the matter. If these are currently allowed by the AUR but shouldn't be I don't mind raising it for wider discussion.

**Comment by AladW** [comment] 2022-01-24 09:36
It's not an AUR policy thing, just that the `aur-srcver` error coincides with the inability to build the packages inside a container. Like you said, commands run outside of packaging functions can't be specified in `makedepends`. 

If a package can't be built inside a container, it's hard to say it follows the Arch packaging guidelines. However, that alone is not sufficient to delete the package - the vast majority of AUR packages do not build in a container.

Regarding `pulseaudio-module-xrdp`: that looks like a very strange case, with the upstream repository mentioning:
> These modules make use of the internal pulseaudio module API. To build them you need access to the pulseaudio sources and configuration.

For a container build, either 1. the `pulseaudio` version can be hardcoded 2. `pulseaudio` is added to `makedepends`, and the pulseaudio sources retrieved manually in `prepare()` 3. the pulseaudio sources are packaged seperately.

For 3, Arch only provides the build files for the `pulseaudio` package (see https://sources.archlinux.org/sources/packages/pulseaudio-15.0-1.src.tar.gz) but not the actual sources (output from `makepkg --allsource`).

**Comment by Earnestly** [comment] 2022-01-24 11:39
If it requires the pulseaudio *source code*, which the PKGBUILD does provide

**Comment by AladW** [comment] 2022-02-05 11:03
Since this is a PKGBUILD problem and some alternatives were proposed, I'll close this issue.

**Closed by AladW** 2022-02-05 11:03 UTC
Labels: question

**Comment by sshaikh** [comment] 2022-02-05 12:55
Thanks, fwiw both PKGBUILDs have been improved and srcver now works for the first one, so happy for this to be closed.

However as an aside I'm not sure if the "builds in a container" qualifier is accurate since as indicated above packer did build in a container, it was just srcver that failed (I presume the containers used for building inherit some kind of basic tooling from the host). Might there be a way for srcver to gain parity with that (I understand that it's doing much less than building so would accept this as a quirk of the design)?

**Comment by AladW** [comment] 2022-02-05 13:22
The gist of it is in the line here: https://github.com/AladW/aurutils/blob/master/lib/aur-srcver#L9

I used `env -i` originally because it was a cheap way to limit accidents from sourcing PKGBUILDs. While one may reasonable expect that someone inspected the PKGBUILD when running `aur-sync`, or did so before running `aur-build`, it is not clear if the same holds for `aur-srcver`. 

`aur-srcver` already takes argument, so I suppose one could add `-E` / `--env` to preserve (a given list of) environment variables.

**Comment by AladW** [comment] 2022-02-05 13:31
https://github.com/AladW/aurutils/pull/906

and `aur-srcver -E PATH` should work with PKGBUILDs like those described.

**Comment by sshaikh** [comment] 2022-02-05 14:37
Sounds like a decent solution. Many thanks!

**Comment by AladW** [comment] 2022-03-02 18:38
I want to add that my argument in https://github.com/AladW/aurutils/issues/898#issuecomment-1030624006 is wrong. `aur-srcver` will run `makepkg -o` no matter what you do. And obviously, `makepkg` can't run with an empty `PATH`. 

As such in the next release `aur-srcver` will preserve the environment. The `-E` flag will stay for compatibility, but it will have no effect.
