### ISSUE TITLE
aur-sync: differentiate between new PKGBUILDs and those without changes

### ISSUE THREAD

**Issue by FichteFoll** [AladW/aurutils#379] opened 2018-04-25 19:31 UTC
I'm using `ranger` as my AUR_PAGER, though I'm not sure whether this might affect vifm too. When I sync a package that exists in the sync cache, vifm used to show a patch for any commits to the aur git repo since the last sync, in addition to the entire folder. When there were no changes, the patch was just empty.

Now, however, empty patches don't show up at all and I can't tell whether I have reviewed a PKGBUILD already or not when it didn't have any changes.

**Comment by AladW** [comment] 2018-04-25 19:43
Isn't this the same behavior as in the release version (1.5)? https://github.com/AladW/aurutils/blob/master/lib/aur-fetch-git#L14

**Comment by FichteFoll** [comment] 2018-04-25 20:16
I've never used the release version, so I wouldn't know. I do recall that I was seeing empty patches with size 0 with vifm before AUR_PAGER was implemented, though.

In the end, the only thing I want is that it doesn't look the same to me for PKGBUILDs I have already viewed and those that didn't have any changes. You could also omit unchanged PKGBUILDs from the review entirely.

**Comment by AladW** [comment] 2018-04-25 20:48
Since I prefer to view non-empty patches, I'll see what I can do on omitting unchanged PKGBUILDs. It's similar to what I'm trying to achieve here: https://github.com/AladW/aurutils/blame/master/contrib/README.md#L57-L59

**Comment by rafasc** [comment] 2018-04-25 20:50
In my opinion the patches are a aurutils courtesy. They're nice to have but aren't part of the build per se. So I do not have a strong opinion if they're present or not. but I disagree with omitting build files, even if they're unchanged.

That being said, they are a good indicator of what needs review. One option we could use is to always produce a "patch".

But what should happen when a new package is built? A diff against the empty tree (diff against 4b825dc642cb6eb9a060e54bf8d69288fbee4904) could work, but would be a bit redundant. 

Maybe having a file explicitly saying "this package is new to aurutils, please review, etc"?

**Comment by AladW** [comment] 2018-04-25 22:04
I guess the sledgehammer approach would be `git-subtree`. "New" packages would be recorded as commits, and these could be saved to some patch file.

**Comment by rafasc** [comment] 2018-04-25 23:26
A much simpler option would be to store something inside the repo to mark it as seen.

Like adding a ref named AURUTILS which points to exact commit the repo was added.

``` sh
# create ref
$ git update-ref AURUTILS $(git rev-parse HEAD) 
# check if exists
$ git rev-parse --verify -q AURUTILS >/dev/null && echo seen || echo new 
```

This AURUTILS ref could even point to an arbitrary  file we create ourselves and store in git's database.

``` sh
# store object
$ git update-ref AURUTILS $(echo "thing to store" | git hash-object -w --stdin)
# print object
$ git cat-file -p AURUTILS
```

**Comment by maximbaz** [comment] 2018-04-25 23:32
Kind-of related to this discussion, I found myself in the following situation a few times already: run `aur sync -u`, see the list of packages (and patches), realize that I don't want to update one of the packages, immediately cancel with `:cq`, run `aur sync -u --ignore pkg1`, be very sad because patches are not shown anymore 😞 

Could we maybe solve this by saving patches to files and showing these patch files among the rest of the files, instead of generating patches during `aur sync`?

-----

> Now, however, empty patches don't show up at all and I can't tell whether I have reviewed a PKGBUILD already or not when it didn't have any changes.

I think having empty patches is not an obvious indication of what needs review, you'd have to do an intersection in your head to figure out which packages don't have a patch.

I'd rather have some empty dummy files that indicate _new_ packages, maybe a file with a name 
`.new.<pkgname>` in the top of the list. Storing something in the repo to mark it as "not new" sounds like a good and easy approach.

-----

> but I disagree with omitting build files, even if they're unchanged.

I would also vote for keeping all build files (including PKGBUILDs) always in the list, even if they haven't changed.

**Comment by FichteFoll** [comment] 2018-04-26 00:25
>Could we maybe solve this by saving patches to files and showing these patch files among the rest of the files, instead of re-generating patches during `aur sync`?

I guess @rafasc's idea for storing refs would be ideal for this. Just store the last reviewed hash as a special ref and run comparisons for patch review against that ref. Once the build succeeded, the ref is updated to HEAD.

---

I agree that declaring something as "new" is much easier to process than "not new but unchanged". The only reason I brought this up in the first place was because it worked like this before, unless I mistook some weird other functionality for this. It seemed consistent, however.

Either way, none of the suggestions for highlighting new packages convinced me so far. What about using symlinks for new packages and prependending "!new." or something similar to the package names? That would also cause them to be sorted at the top, for example, so you could quickly go over them sequentially and then proceed with diffs.

**Comment by rafasc** [comment] 2018-04-26 00:26
> `.new.<pkgname>` in the top of the list. Storing something in the repo to mark it as "not new" sounds like a good and easy approach.

This is what I meant when I said:
>having a file explicitly saying "this package is new"

 thanks for explaining it better than me :)

---

The issue with `:cq` is indeed annoying. I think we can solve it if we make the AURUTILS git ref point to the last commit the user has seen. And we only update it if the editor exits successfully.

**Comment by AladW** [comment] 2018-04-26 17:47
Well, if you guys want to express your ideas as a PR, I'd happily take a look. :+1:

**Comment by AladW** [comment] 2018-05-01 23:27
Spending some more time on this, what I understand has been suggested so far:
* Use an `AURUTILS` ref inside each `.git` directory, update it to HEAD if the editor has exited successfully.
  * Updating it after the _build_ has succeeded sounds more complicated, and the PKGBUILD has been executed in full at build start anyway.
  * Generate diffs based on this ref, see https://github.com/AladW/aurutils/issues/379#issuecomment-384464915
  * Can something equivalent be done for `aur-fetch-snapshot`?
* If a new package has been cloned, create a symlink with a `!new` prefix.
  * Assumes symlinks are used to begin with, i.e. `AUR_PAGER` is set.

**Comment by FichteFoll** [comment] 2018-05-02 00:40
>Updating it after the *build* has succeeded sounds more complicated, and the PKGBUILD has been executed in full at build start anyway.

@maximbaz's use case was that he noticed he didn't want to update a package and would not get to see diffs again after excluding it (or similar). I guess you could work around this by killing the process tree, though?
I would personally prefer to update the ref after the build has finshed as it seems like the more natural process to me (diff to last successful build rather than last review), but I don't feel strongly about it. Whether or not the PKGBUILDs have been executed already doesn't really concern me since that should be expected once the editor has been closed.

I wonder whether there would be a cleaner way to abort a sync without having to kill the process(es).

>Assumes symlinks are used to begin with, i.e. `AUR_PAGER` is set.

Well, we have full control over what is being sent to vifm's stdin, so I don't see why making symlinks for this case wouldn't work there.

Other than that, looks good.

**Comment by maximbaz** [comment] 2018-05-02 07:42
> Use an AURUTILS ref inside each .git directory, update it to HEAD if the _editor_ has exited successfully.

I think this will be perfect, because the other scenario is:

1. Run `aur sync -u`, it detects 2 packages, shows patches.
2. Review patches, exit editor, start the build.
3. 15 minutes later the build fails on the first package.
4. Restart `aur sync -u`, and by this time there are 3 packages that need update - I already reviewed the previous two, so I would expect to see only one patch, for a package that I haven't reviewed yet.

By exiting with `:cq` I kind of intentionally indicate "I'm not done here, will get back to this", while by exiting with `:q` I send a message "I'm done with review, everything is fine".

**Comment by AladW** [comment] 2018-05-02 11:58
>By exiting with :cq I kind of intentionally indicate "I'm not done here, will get back to this", while by exiting with :q I send a message "I'm done with review, everything is fine".

That sounds like a good argument. Besides the required git commands in https://github.com/AladW/aurutils/issues/379#issuecomment-384464915 we'd also need to think on where to add them. Ideally this would be part of `aur-fetch-git`, but that program is unaware of `vifm` or any other viewing mechanism. Perhaps add a flag to update the ref to HEAD? (e.g. `aur-fetch-git -U`)

**Comment by rafasc** [comment] 2018-05-02 13:52
But let's consider that not every `AUR_PAGER` will support 'exit with error' as `vim` and `vifm` does with `:cq`.

The selfish me would say that those users can wrap their pagers in a script with an prompt at the end to decide if the review was completed or not (exiting with or without error, accordingly). `aurutils` itself could prompt, decoupling the logic from AUR_PAGER exit codes, but again, the selfish `vi{,f}m`user in me partially dislikes the extra step.

We can also make use of the `git reflog`(`git reflog HEAD@{u}`)
`git diff HEAD HEAD@{u}@{1}` would show what's different between what is currently checked out and the previous fetch. (here previous means the previous fetch that brought changes). This could be interesting if the if the user is interested in seeing the patch regardless if it is marked as seen.

But I am thinking about this on a vacuum. I did not consider how this could be integrated in the tool flow.

**Comment by rafasc** [comment] 2018-05-02 15:12
Abstracting the viewer logic into an `aur-viewer--helper` (#382) maybe isn't a bad idea either.

That way we could support known viewers that doesn't "exit with error" by making an additional prompt. Similar how git handles [mergetools](https://github.com/git/git/tree/master/mergetools), trusting the exit code to mark files as merged. It could also define how the viewer opens the files ( related to #51 ). etc.

We could add another layer on top of this, allowing users to optionally make their own `aur-viewer--script`. That would be called by `aur-viewer--helper` if `AUR_PAGER==script`. And it's up to them to define what's considered exit success.

And from the point of view of `aur-sync` it would just trust the exit code regardless.
i.e. `aur viewer--helper && aur fetch-git -U`

But I am getting side-tracked here, and I think this is content for another issue/PR. 

For now, I agree with trusting the exit code of `AUR_PAGER`. Users relying on custom pagers should make a thin wrapper ensuring the pager exits accordingly.

**Comment by AladW** [comment] 2018-05-02 16:12
|The selfish me would say that those users can wrap their pagers in a script with a prompt at the end to decide if the review was completed or not (exiting with or without error, accordingly)

I agree with this logic. Any change for compability with viewers I don't use should not be a downgrade with viewers I do use. (in the case of `AUR_PAGER`, it was an upgrade due to preserved state in `/tmp/view`). 

Separating viewer functionality to a separate script is something we could do at some point, but for now I'd say there's enough wiggle room with setting `AUR_PAGER`. After all, by definition `aurutils` expects some DIY from its users.

`git reflog` is definitely an interesting idea and if we can rely on it alone, simpler than considering exit codes or additional `aur-fetch-git` flags.

**Comment by rafasc** [comment] 2018-05-08 19:12
A super ugly PoC: https://github.com/AladW/aurutils/compare/master...rafasc:wip_pkg_review

Another approach would be to allow the user to specify the base of the comparison.

```sh
merge_upstream() {
    git fetch -v >&2

    BASE=${user_ref:-HEAD}
    if [[ $(git rev-parse $BASE) != $(git rev-parse '@{upstream}') ]]; then
        # only print log on upstream changes
        git --no-pager log --patch --stat "$BASE..@{upstream}" >> "${1:-/dev/stdout}"

        # discard any local changes (#349)
        git reset --hard HEAD@{upstream} >&2
    fi
}
```

An user that previously `:cq`'d could just specify another revision as a base. It's much simpler but still requires a flag addition. I think I prefer the benefits of the former.

**Comment by AladW** [comment] 2018-05-09 10:30
How about print the revision on `:cq` to allow the user to easily copy paste it? (and pass on accordingly through an env var or otherwise)

**Comment by rafasc** [comment] 2018-05-09 11:27
the reset --hard already dumps that info:
```
fca39af..69cfd33  master     -> origin/master
HEAD is now at 69cfd33 Bump to 49.4.68
```
where `fca39af` is the revision we would need to pass. This would solve the issue with `:cq` but new pkgs and no changes would still look the same, i.e. nothing shown.

**Comment by AladW** [comment] 2018-05-09 12:51
In that case I'll need some time to think on the approach taken. Feel free to open a PR where we can continue to discuss this.

**Comment by AladW** [comment] 2018-08-24 07:13
>Kind-of related to this discussion, I found myself in the following situation a few times already: run aur sync -u, see the list of packages (and patches), realize that I don't want to update one of the packages, immediately cancel with :cq, run aur sync -u --ignore pkg1, be very sad because patches are not shown anymore disappointed

I've added the `AUR_VIEWDIR` variable, so you can review the patches in this directory after exiting the file manager.

**Comment by darkfeline** [comment] 2019-01-24 09:09
This bug seems to have grown and included many other requests.  Was the original bug ever solved, that is "differentiate between new PKGBUILDs and those without changes"?

(Regarding "Funnily enough, once more vim/vifm have the monopoly on sensible features - not even ranger supports :cq.", I can attest that Emacs/Dired supports this feature, and I agree that the onus is on the viewer command to support non-zero exit and not aurutils.)

**Comment by AladW** [comment] 2019-07-31 19:30
This should be covered by https://github.com/AladW/aurutils/commit/a45fdf5964b59a9787c99a53ae844fabc39f688d#diff-5735282db1c278eacee9db868b359699: "new" PKGBUILDs have a patch file which includes all contents (of the AUR repository). Thoughts?

**Comment by rafasc** [comment] 2019-07-31 20:22
I think we can close this. As you said, we can differentiate them now. 
New has a patch, no changes doesn't.
 If a better solution eventually comes up, we can open a new issue/PR.

---
As a footnote:
Since we no longer show commit messages, `vifm` can be configured to show them.
See https://github.com/AladW/aurutils/pull/565#issuecomment-491629079

**Comment by AladW** [comment] 2019-07-31 23:04
For some reason, after posting this comment, on "new" packages the patches no longer show up... all I remember changing is rebuilding aurutils-git to the latest revision. :thinking:

**Comment by maximbaz** [comment] 2019-08-01 09:28
Yeah it doesn't really work on latest master, `aur sync <newpkg>` will open `vifm` and there will be no patch, but if you `:cq` and then `aur sync <newpkg>` a second time, then you'll get a full patch. I agree having the full patch is a nice solution, if only it worked on the first try 😉

**Comment by AladW** [comment] 2019-08-01 09:36
@rafasc any ideas on solving this?

**Comment by rafasc** [comment] 2019-08-01 13:26
yes: #586

**Comment by AladW** [comment] 2019-08-04 07:49
`aur-fetch` seems to be broken in other ways. In particular, I `only` get patches for "new" content; diffs for existing repositories are simply ignored. This holds both for the master branch and #586.

**Comment by rafasc** [comment] 2019-08-07 16:59
@AladW I cannot reproduce that issue. Can you give me a minimal example?

**Comment by AladW** [comment] 2020-07-05 11:07
With #711 merged this should be straightforward to implement in an `aur` script. I believe @maximbaz had one for `nnn`, it could likely be adapted to `ranger` as well.

**Comment by maximbaz** [comment] 2020-07-07 11:39
Here's a version for `nnn` for reference: https://github.com/maximbaz/dotfiles/commit/425faf68d75861356f16f7f5a8ef5d8bc0a49f3f

Given that in `nnn` there is no way to provide a custom order, all new packages are prefixed with an underscore. Looks like this:

![image](https://user-images.githubusercontent.com/1177900/86774874-37dadf00-c057-11ea-8b86-af49fd84db10.png)

**Comment by AladW** [comment] 2020-10-03 12:24
The example by @maximbaz should be easy to adapt to other file managers. Feel free to reopen if not.

**Closed by AladW** 2020-10-03 12:24 UTC
Labels: enhancement

**Comment by FichteFoll** [comment] 2020-10-18 21:34
I used the following command to transition to the new "view_db" format:
```sh
$ cd "${XDG_CACHE_DIR:-$HOME/.cache}/aurutils/sync"; for pkg in *; do pushd -q "$pkg"; git show-ref HEAD | cut -d" " -f1 > "${XDG_DATA_HOME:-$HOME/.local/share}/aurutils/view/$pkg"; popd -q; done;
```
and created a custom command in ranger that roughly mirrors the logic from @maximbaz's script but marks new packages instead of prefixing their names with a character. https://github.com/FichteFoll/dotfiles/commit/a5299dae74a094245ab14657b3687dd9ac7050b0
