### ISSUE TITLE
`aur depends` reports unused/unnecessary AUR dependencies

### ISSUE THREAD

**Issue by eclairevoyant** [AladW/aurutils#1035] opened 2022-10-25 18:24 UTC
Tested using `aur version 10b-215-geb20949b`.
When a package has genericised dependencies (such as `jack`) that are provided by packages in the main repos (`jack2` and `pipewire-jack` in `extra`), but the exact named dependency is [in the AUR](https://aur.archlinux.org/packages/jack), `aur-depends` incorrectly returns the AUR package.

For example, `aur depends 6pm` returns:
```
celt
jack
6pm
```

However I would expect it to return no AUR dependencies (other than itself, `6pm`).

This is because when running `makechrootpkg -- -s`, pacman correctly pulls in the dependency from the main repos (it picks `extra/jack2` by default).

The reason I'm reporting this as a possible bug is because when running `aur sync -c 6pm`, it downloads the `PKGBUILD`s for `celt` and `jack`, but in the build step it doesn't even use them and uses `extra/jack2` instead.

I don't have `celt` or `jack` in my local repo, so downloading them is a waste of space/bandwidth imo.

I also didn't find anything in `man aur-depends` to prefer existing repos.
[`aurutils.log`](https://github.com/AladW/aurutils/files/9862931/aurutils.log) attached for `aur depends 6pm`.

**Comment by AladW** [comment] 2022-10-26 14:24
I get the following `aur-sync` output:
```
==> Using [alad] repository
sync: packages ignored: matlab-support 
  -> 6pm (none) -> 0.9-1
  -> celt (none) -> 0.11.3-5
  -> jack (none) -> 0.126.0-4
dependency jack satisfied by extra/jack2
dependency libjack.so satisfied by extra/jack2
dependency libjacknet.so satisfied by extra/jack2
dependency libjackserver.so satisfied by extra/jack2
dependency jack satisfied by extra/pipewire-jack
dependency libjack.so satisfied by extra/pipewire-jack
dependency libjackserver.so satisfied by extra/pipewire-jack
dependency libjacknet.so satisfied by extra/pipewire-jack
==> Retrieving package files
Already up to date.
Cloning into '6pm'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), done.
59682aa (Initial commit, 2018-09-08)
6pm	6pm
celt	celt
```
Considering the AUR does not expose `provides` on its API, filtering out dependencies after downloading all possible ones is the best `aur-sync` can do. Right now this isn't done transitively: see https://github.com/AladW/aurutils/issues/592.

**Comment by eclairevoyant** [comment] 2022-10-26 17:05
Not sure what you mean here; the AUR does expose provides via its API?
```
$ aur query -t info jack2-git
{"resultcount":1,"results":[{"Conflicts":["jack","jack2"],"Depends":["db","gcc-libs","glibc","opus","libasound.so","libdbus-1.so","libsamplerate.so","libsystemd.so"],"Description":"The JACK low-latency audio server","FirstSubmitted":1330892306,"Groups":["pro-audio"],"ID":1122265,"Keywords":["audio","cv","jack","midi"],"LastModified":1659702892,"License":["GPL2","LGPL2.1"],"Maintainer":"milkii","MakeDepends":["alsa-lib","dbus","doxygen","expat","git","libffado","libsamplerate","opus","systemd","waf"],"Name":"jack2-git","NumVotes":8,"OptDepends":["a2jmidid","libffado","jack-example-tools","jack2-dbus","jack2-docs","realtime-privileges"],"OutOfDate":null,"PackageBase":"jack2-git","PackageBaseID":57278,"Popularity":0,"Provides":["jack","jack2","libjack.so","libjacknet.so","libjackserver.so","jack2=1.9.21"],"URL":"http://jackaudio.org/","URLPath":"/cgit/aur.git/snapshot/jack2-git.tar.gz","Version":"2:1.9.21.r14.gd732afcb-1"}],"type":"multiinfo","version":5}
```

Also, we don't need to look at `provides` in the AUR here. In fact, if there was no package called `jack` in the AUR, the AUR script would be behaving correctly because it would just pull in `extra/jack2` - this only requires looking at `provides` from repos, which is already a given.

I'm suggesting that `aur-depends` (and therefore `aur-sync`) should prioritise dependencies in repos because that's what `makepkg` does. There's no reason to download `jack` from the AUR when we have two other repo packages that can satisfy the dependency.

**Comment by AladW** [comment] 2022-10-26 18:33
> Not sure what you mean here; the AUR does expose provides via its API?

By provides I mean _provided by_, or "required by" as labeled on the website.

> This is a direct dependency, not a transitive one,

`jack` is filtered out because it's provided by `jack2` in the repos, but `celt` is still a target because it's a `makedepends` for `jack` in AUR. Ideally a removal of  `jack` from the target list also results in any of its (AUR) build dependencies being removed. [1]

Anyway, I guess the suggestion is to include `aur-repo-filter` in `aur-depends`. I'm not sure what that would bring to the table, since the tools have distinct purposes. `depends` retrieves dependency information recursively from AUR, `repo-filter` removes the stuff you don't need based on what's in your `pacman` repositories. 

`aur-sync` wraps both and runs `aur-repo-filter` _before_ running `aur-fetch`, so that `jack` is effectively not downloaded. (My first comment was unclear/wrong about that.) But because of [1], it's AUR `makedepends` are.

**Comment by eclairevoyant** [comment] 2022-10-26 19:03
Yeah, I guess that's effectively the suggestion. To me the benefit is having less PKGBUILDs to review, especially if I'm installing or updating a lot of packages. `aur sync` doesn't download `jack` (which is good) but I do still end up reviewing the `PKGBUILD`s for `celt` and `jack` in this scenario. Sure, in this case I know that there's packages providing `jack` in the repos, but if it was an obscure dependency I may not have known that.

Regardless, I'll take a look at that thread, thanks.

**Comment by AladW** [comment] 2023-01-13 19:07
I'll close this as a duplicate of #592 then. Thanks for the input.

**Closed by AladW** 2023-01-13 19:07 UTC
Labels: question
