### ISSUE TITLE
`depends`: Undefined value as HASH reference.

### ISSUE THREAD

**Issue by patlefort** [AladW/aurutils#1112] opened 2023-09-17 14:10 UTC
Example command: `aur depends lib32-blas python`.

Result in: `Can't use an undefined value as a HASH reference at /usr/lib/aurutils/aur-depends line 116.`

AUR_DEBUG output:

```
aur version 18.1
query: [1] lib32-blas python
'curl' '-A' 'aurutils' '-fgLsSq' 'https://aur.archlinux.org/rpc/v5/info' '--data-raw' '&arg[]=lib32%2Dblas&arg[]=python'
query: [2] lib32-gcc-libs blas gcc-fortran cmake python
'curl' '-A' 'aurutils' '-fgLsSq' 'https://aur.archlinux.org/rpc/v5/info' '--data-raw' '&arg[]=lib32%2Dgcc%2Dlibs&arg[]=blas&arg[]=gcc%2Dfortran&arg[]=cmake&arg[]=python'
query: filtering results
Can't use an undefined value as a HASH reference at /usr/lib/aurutils/aur-depends line 116.
```

**Comment by AladW** [comment] 2023-09-18 12:17
The problem is in this block of code:
```perl
    # Merge reverse dependencies for purely virtual targets, with corresponding
    # packages specified on the command-line
    for my $name (keys %{$results}) {
        if ($results->{$name} eq 'None' and defined $shlibs->{$name}) {
            my $prov = $shlibs->{$name}[0];


            $mod{$prov}->{'RequiredBy'} = {
                %{$mod{$prov}->{'RequiredBy'}}, %{$reqby->{$prov}}
            };
        }
    }
```

**Comment by AladW** [comment] 2023-09-18 13:47
Fixed in `master`, thanks for the report

**Closed by AladW** 2023-09-18 13:47 UTC
Labels: (ノಠ益ಠ)ノ彡┻━┻, regression-test
