### ISSUE TITLE
error: --local, --sync, and --cache cannot be used as filters

### ISSUE THREAD

**Issue by kattjevfel** [AladW/aurutils#804] opened 2021-01-22 16:02 UTC
I'm always getting the following when doing, well.. any action really. It's not really interfering with anything, but I got fed up with seeing this all the time.

To keep it simple here's trying to sync an already up-to-date package:
```
katt@main ~ » aur sync ffmpeg-headless                 
==> Using [custom] repository
warning: config /etc/pacman.conf line 24: unknown option 'ParallelDownloads'
warning: config /etc/pacman.conf line 24: unknown option 'ParallelDownloads'
error: --local, --sync, and --cache cannot be used as filters
    there is nothing to do
```

The first error is simply due to running pacman-git, why exactly it reads /etc/pacman.conf I don't know, it happens even as I specify another config.

aur version 3.1.2-19-gad5b985
[aurutils.log](https://github.com/AladW/aurutils/files/5856991/aurutils.log)

**Comment by Earnestly** [comment] 2021-01-22 19:47
pacutils is responsible for those warnings and error. It's unfortunate that pacutils does not prefix its name to the error message as that would make it clearer.

It seems like the closing of standard input (`<&-`) is now upsetting it.  I remember pacutils tools being a little picky about this situation but removing `<&-` in the simple reproducer seems to help:

```sh
% xargs -a <(printf -- --satisfies=ffmpeg-headless) pacsift --sync <&- | cat
warning: config /etc/pacman.conf line 38: unknown option 'ParallelDownloads'
error: --local, --sync, and --cache cannot be used as filters
```

**Comment by AladW** [comment] 2021-01-23 09:59
Is this reproducible with pacman 5.2.2 and pacutils 0.10?

**Comment by kattjevfel** [comment] 2021-01-23 11:58
> Is this reproducible with pacman 5.2.2 and pacutils 0.10?

Nope, I instead get this, which I don't know is normal or not (I've never used aurutils with stable pacman)
```
katt@main ~ » aur sync ffmpeg-headless
==> Using [custom] repository
dependency libavcodec.so satisfied by ffmpeg-headless
dependency libavdevice.so satisfied by ffmpeg-headless
dependency libavfilter.so satisfied by ffmpeg-headless
dependency libavformat.so satisfied by ffmpeg-headless
dependency libavutil.so satisfied by ffmpeg-headless
dependency libpostproc.so satisfied by ffmpeg-headless
dependency libswresample.so satisfied by ffmpeg-headless
dependency libswscale.so satisfied by ffmpeg-headless
dependency ffmpeg satisfied by ffmpeg-headless
    there is nothing to do
```

[aurutils.log](https://github.com/AladW/aurutils/files/5860146/aurutils.log)

**Comment by AladW** [comment] 2021-01-23 13:03
Yes, that's the expected behavior. Seems like this is an issue that 
should be reported to pacutils.

**Comment by AladW** [comment] 2021-05-30 16:09
Going by IRC convo this no longer seems an issue (and pacutils was updated for pacman 6).

**Comment by rbellamy** [comment] 2021-06-04 00:59
Closing this issue must have angered the gremlins.

Cuz I have the following versions, and I'm seeing this error for the first time:

**Installed:**
```shell
2021-06-03 17:49:27 
rbellamy@eanna i ~ % pacman -Qi pacutils
Name            : pacutils
Version         : 0.11.0-2
Description     : Helper tools for libalpm
Architecture    : x86_64
URL             : https://github.com/andrewgregory/pacutils
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : pacman
Optional Deps   : None
Required By     : aurutils
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 490.27 KiB
Packager        : Allan McRae <allan@archlinux.org>
Build Date      : Mon 24 May 2021 04:42:37 PM PDT
Install Date    : Thu 03 Jun 2021 03:49:54 PM PDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

2021-06-03 17:54:36 
rbellamy@eanna i ~ % pacman -Qi pacman
Name            : pacman
Version         : 6.0.0-2
Description     : A library-based package manager with dependency support
Architecture    : x86_64
URL             : https://www.archlinux.org/pacman/
Licenses        : GPL
Groups          : base-devel
Provides        : libalpm.so=13-64
Depends On      : bash  glibc  libarchive  curl  gpgme  pacman-mirrorlist  archlinux-keyring
Optional Deps   : perl-locale-gettext: translation support in makepkg-template [installed]
Required By     : appstream-glib  arch-install-scripts  expac  pacman-contrib  pacutils  pkgfile
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 4.61 MiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : Thu 20 May 2021 11:38:55 AM PDT
Install Date    : Thu 03 Jun 2021 03:49:43 PM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

2021-06-03 17:54:40 
rbellamy@eanna i ~ % pacman -Qi aurutils
Name            : aurutils
Version         : 3.1.2-2
Description     : helper tools for the arch user repository
Architecture    : any
URL             : https://github.com/AladW/aurutils
Licenses        : custom:ISC
Groups          : None
Provides        : None
Depends On      : git  jq  pacutils  curl
Optional Deps   : bash-completion: bash completion [installed]
                  zsh: zsh completion [installed]
                  devtools: aur-chroot [installed]
                  vifm: default pager [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 98.13 KiB
Packager        : Unknown Packager
Build Date      : Thu 07 Jan 2021 10:26:48 AM PST
Install Date    : Thu 07 Jan 2021 10:26:50 AM PST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : SHA-256 Sum
```

**In action:**
```shell
2021-06-03 17:56:57 
rbellamy@eanna i ~ % aur sync gnome-web-photo
==> Using [eanna] repository
  -> gnome-web-photo: (none) -> 0.10.6-5
error: --local, --sync, and --cache cannot be used as filters
==> Retrieving package files
Cloning into 'gnome-web-photo'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 21 (delta 0), reused 21 (delta 0), pack-reused 0
Unpacking objects: 100% (21/21), 11.79 KiB | 65.00 KiB/s, done.
Running makepkg --syncdeps --clean
==> Making package: gnome-web-photo 0.10.6-5 (Thu 03 Jun 2021 05:57:11 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading gnome-web-photo-0.10.6.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  205k  100  205k    0     0   155k      0  0:00:01  0:00:01 --:--:--  641k
==> Validating source files with sha256sums...
```

**Comment by AladW** [comment] 2021-06-04 09:38
It seems something in pacman that broke pacutils filters. I can only 
think of running git bisect on pacman to see which commit broke it.

https://wiki.archlinux.org/title/Bisecting_bugs_with_Git

**Comment by CyberShadow** [comment] 2021-06-07 03:28
It's because `alpm_initialize` now creates a socket, which gets allocated at fd 0 (since it's free when the tool is invoked with `<&-`).

https://github.com/andrewgregory/pacutils/pull/45

**Comment by Izzette** [comment] 2021-06-12 15:20
Couldn't we just call pacsift with `< /dev/null` instead of `<&-` to work around the issue?

**Comment by CyberShadow** [comment] 2021-06-13 08:15
No, because, pacsift will see `/dev/null` as a file / stream like any other, and will think that you are asking it to filter a list of packages (which happens to be empty).

Alad suggested on IRC `script --return --quiet -c ... /dev/null`, which does seem to work.

**Comment by AladW** [comment] 2021-06-17 09:13
I spent some more time on this, and `script` has weird behavior when piping the output. Same for `socat` 👍 
```
$ echo pacman | ./aur-repo-filter 
'nable to find package 'core/pacman
```
`unbuffer` works fine however. It just adds `tcl` and `expect` as a dependency.

**Comment by AladW** [comment] 2021-06-17 09:25
Please test #818.

**Closed** 2021-06-17 19:23 UTC
Labels: upstream
