### ISSUE TITLE
Shellcheck failures in check()

### ISSUE THREAD

**Issue by tadfisher** [AladW/aurutils#231] opened 2017-04-12 03:17 UTC
```
==> Making package: aurutils 1.5.3-1 (Tue Apr 11 20:14:27 PDT 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (1) shellcheck-0.4.6-2

Total Download Size:    1.75 MiB
Total Installed Size:  14.86 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 shellcheck-0.4.6-2-x86_64         1794.2 KiB  7.12M/s 00:00 [################################] 100%
(1/1) checking keys in keyring                               [################################] 100%
(1/1) checking package integrity                             [################################] 100%
(1/1) loading package files                                  [################################] 100%
(1/1) checking for file conflicts                            [################################] 100%
(1/1) checking available disk space                          [################################] 100%
:: Processing package changes...
(1/1) installing shellcheck                                  [################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Retrieving sources...
  -> Cloning aurutils-1.5.3 git repo...
Cloning into bare repository '/home/tad/.cache/aursync/aurutils/aurutils-1.5.3'...
remote: Counting objects: 6089, done.
remote: Total 6089 (delta 0), reused 0 (delta 0), pack-reused 6089
Receiving objects: 100% (6089/6089), 830.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4225/4225), done.
==> Validating source files with sha256sums...
    aurutils-1.5.3 ... Skipped
==> Extracting sources...
  -> Creating working copy of aurutils git repo...
Cloning into 'aurutils-1.5.3'...
done.
Switched to a new branch 'makepkg'
==> Starting check()...

In bin/aurchain line 55:
        if [[ ${target[@]} ]]; then
              ^-- SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).


In bin/aursift line 34:
    siftargs+=(--satisfies="$p")
               ^-- SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.


In bin/aursift line 38:
if [[ ${pkgset[@]} ]]; then
      ^-- SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).


In bin/aursift line 40:
        siftargs+=(--repo="$p")
                   ^-- SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.


In bin/aursift line 50:
if [[ ${query[@]} ]]; then
      ^-- SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).


In bin/aursync line 129:
    if [[ ${avail[@]} ]]; then
          ^-- SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).

make: *** [Makefile:9: check] Error 1
==> ERROR: A failure occurred in check().
    Aborting...
==> Removing installed dependencies...
checking dependencies...

Packages (1) shellcheck-0.4.6-2

Total Removed Size:  14.86 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
removing shellcheck...
```

**Comment by AladW** [comment] 2017-04-13 13:30
Duplicate of: #228 

I've removed make check from the AUR PKGBUILD, since the shellcheck errors are purely superficial and there may be no new release in a while.

**Closed** 2017-04-13 13:30 UTC
Labels: duplicate
