### ISSUE TITLE
aur chroot: uses pacserve to obtain *.db

### ISSUE THREAD

**Issue by sprnza** [AladW/aurutils#699] opened 2020-03-20 09:47 UTC
See the [aurutils.log](https://github.com/AladW/aurutils/files/4358793/aurutils.log) and the only place where I see pacserve configure is host's pacman.conf. How could I solve this?

pacman-aur.conf
```
# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#                                             
# REPOSITORIES                                
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#                                             
# Repository entries are of the format:
#       [repo-name]                           
#       Server = ServerName
#       Include = IncludePath
#                                             
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#                                             

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

#[testing]                                    
#Include = /etc/pacman.d/mirrorlist

[core]                                        
Include = /etc/pacman.d/mirrorlist

[extra]                                       
Include = /etc/pacman.d/mirrorlist

#[community-testing]                          
#Include = /etc/pacman.d/mirrorlist

[community]                                   
Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]                                     
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
```

```
speran ➜  ~ pacconf --config=/usr/share/devtools/pacman-aur.conf               
[options]
RootDir = /
DBPath = /var/lib/pacman
CacheDir = /var/cache/pacman/pkg
HookDir = /etc/pacman.d/hooks
GPGDir = /etc/pacman.d/gnupg
LogFile = /var/log/pacman.log
HoldPkg = pacman
HoldPkg = glibc
Architecture = x86_64
CleanMethod = KeepInstalled
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[core]
Usage = All
Server = http://archlinux.zepto.cloud/core/os/x86_64
Server = http://mirror.truenetwork.ru/archlinux/core/os/x86_64
Server = http://mirror.rol.ru/archlinux/core/os/x86_64
Server = https://mirror.rol.ru/archlinux/core/os/x86_64
Server = http://mirror.yandex.ru/archlinux/core/os/x86_64
Server = https://mirror.yandex.ru/archlinux/core/os/x86_64
[extra]
Usage = All
Server = http://archlinux.zepto.cloud/extra/os/x86_64
Server = http://mirror.truenetwork.ru/archlinux/extra/os/x86_64
Server = http://mirror.rol.ru/archlinux/extra/os/x86_64
Server = https://mirror.rol.ru/archlinux/extra/os/x86_64
Server = http://mirror.yandex.ru/archlinux/extra/os/x86_64
Server = https://mirror.yandex.ru/archlinux/extra/os/x86_64
[community]
Usage = All
Server = http://archlinux.zepto.cloud/community/os/x86_64
Server = http://mirror.truenetwork.ru/archlinux/community/os/x86_64
Server = http://mirror.rol.ru/archlinux/community/os/x86_64
Server = https://mirror.rol.ru/archlinux/community/os/x86_64
Server = http://mirror.yandex.ru/archlinux/community/os/x86_64
Server = https://mirror.yandex.ru/archlinux/community/os/x86_64
```

**Comment by AladW** [comment] 2020-03-28 09:33
I suspect this is related to the convoluted mirror mechanic in `arch-nspawn` (https://git.archlinux.org/devtools.git/tree/arch-nspawn.in#n66). `aur-chroot` only uses `pacman-aur.conf` for bind mounts, and otherwises passes on the config to `arch-nspawn` and `mkarchroot`. Please check if you have the same issues with `extra-x86_64-build`.

**Comment by sprnza** [comment] 2020-04-01 07:02
Hi! Thanks for the reply!
You are saying:
> Please check if you have the same issues with extra-x86_64-build
But I don't get it. Could you elaborate please?

**Comment by AladW** [comment] 2020-04-07 20:01
`extra-x86_64-build` is the "standard" devtools command to build packages in a container. So if you run the command in some PKGBUILD directory and get the same error, it's unlikely to be an aurutils problem.

**Comment by zoqaeski** [comment] 2021-06-07 01:06
I'm getting this exact error, and I was able to build a package using the `extra-x86_64-build` script. If I remove the pacserve sources from my host `pacman.conf`, then `aur build -c -d my-repository` works as expected.

**Comment by AladW** [comment] 2021-06-17 09:10
I've never used pacserve. Can you give some precise steps on how to reproduce the issue?

**Comment by zoqaeski** [comment] 2021-06-19 13:35
When I posted that comment, I was able to build a package with `extra-x86_64-build` script, and then a few days later I tried to build a different package and it failed due to unresolvable dependencies. The mirror copying code in `arch-nspawn` definitely seemed to be to blame, and I was able to figure out a workaround by by (clumsily) patching it to delete any lines that contained `localhost:15678` in the mirror copy (as that port is the default used by pacserve). I don't think my patch would be accepted upstream, as pacserve isn't in the official repositories. 

So depending on the package and its dependencies, sometimes this fails and sometimes it doesn't, but its reproducible with both `aur build` and `extra-x86_64-build`.

That all being said, if you do want to reproduce this issue, the steps are fairly simple:

1. Install pacserve and configure it so that pacman looks for packages on the pacserve mirror first, e.g.
    ```
    [core]
    Include = /etc/pacman.d/pacserve
    Include = /etc/pacman.d/mirrorlist

    [extra]
    Include = /etc/pacman.d/pacserve
    Include = /etc/pacman.d/mirrorlist

    #[community-testing]
    #Include = /etc/pacman.d/mirrorlist

    [community]
    Include = /etc/pacman.d/pacserve
    Include = /etc/pacman.d/mirrorlist

    # If you want to run 32 bit applications on your x86_64 system,
    # enable the multilib repositories as required here.

    #[multilib-testing]
    #Include = /etc/pacman.d/mirrorlist

    [multilib]
    Include = /etc/pacman.d/pacserve
    Include = /etc/pacman.d/mirrorlist
    ```
2. Start pacserve and update the system.
3. Try building some packages with `extra-x86_64-build` and `aur build -c`

If a package is going to fail, you will get warnings in the output from the pacman instance in the chroot that it cannot retrieve some files due to a 404 error:
```
error: failed retrieving file 'a-dependency-package.pkg.tar.zst' from localhost:15678 : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
```

I haven't figured out a pattern for why it fails sometimes and doesn't fail on other occasions. The patch to `arch-nspawn` to fix the issue is:
```
314c314
< host_mirrors=($($pacconf_cmd --repo extra Server 2> /dev/null | sed -r 's#(.*/)extra/os/.*#\1$repo/os/$arch#'))
---
> host_mirrors=($($pacconf_cmd --repo extra Server 2> /dev/null | sed -r -e 's#(.*/)extra/os/.*#\1$repo/os/$arch#' -e '\#^(https?://localhost:15678/.*)#d'))
327c327
< 		--repo $line Server | sed -r 's#(.*/)[^/]+/os/.+#\1#')
---
> 		--repo $line Server | sed -r -e 's#(.*/)[^/]+/os/.+#\1#' -e '\#^(https?://localhost:15678/.*)#d')
```

**Comment by AladW** [comment] 2022-03-02 22:46
`devtools` has had a release since. Is this still a problem? Either way, since there's nothing I can do about `devtools` problems on the `aurutils` side, I'll close this issue again. You might however want to keep an eye on #909.

**Closed by AladW** 2022-03-02 22:46 UTC
Labels: devtools

**Comment by zoqaeski** [comment] 2022-07-06 13:54
I haven't had the issue as I've been maintaining my own private patch of `arch-nspawn` to alter the lines that cause the problem. Subsequent `devtools` releases haven't changed the logic in that part of the script, so I don't think the issue has been remedied upstream.
